-- MySQL Script generated by MySQL Workbench
-- Sun Dec 1 16:33:43 2024
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

USE `FEIG`;

ALTER TABLE `Instituicao` ADD CONSTRAINT `PK_Instituicao` PRIMARY KEY (`CNPJ`);
ALTER TABLE `Voluntarios` ADD CONSTRAINT `PK_Voluntarios` PRIMARY KEY (`CNPJ_Instituicao`, `CPF`);
ALTER TABLE `Doacao` ADD CONSTRAINT `PK_Doacao` PRIMARY KEY (`ID`);
ALTER TABLE `Doador` ADD CONSTRAINT `PK_Doador` PRIMARY KEY (`CPF`);
ALTER TABLE `Beneficiario` ADD CONSTRAINT `PK_Beneficiario` PRIMARY KEY (`CPF`);
ALTER TABLE `ProjetoAssistencial` ADD CONSTRAINT `PK_ProjetoAssistencial` PRIMARY KEY (`ID`);
ALTER TABLE `Ajuda` ADD CONSTRAINT `PK_Ajuda` PRIMARY KEY (`ID_ProjetoAssistencial`, `CPF_Beneficiario`);
ALTER TABLE `Evento` ADD CONSTRAINT `PK_Evento` PRIMARY KEY (`ID`);
ALTER TABLE `Relatorio` ADD CONSTRAINT `PK_Relatorio` PRIMARY KEY (`ID`);

ALTER TABLE `Voluntarios` ADD CONSTRAINT `FK_Voluntarios_Instituicao`
    FOREIGN KEY (`CNPJ_Instituicao`)
    REFERENCES `Instituicao` (`CNPJ`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE;
	
ALTER TABLE `Doacao` ADD CONSTRAINT `FK_Doacao_Evento`
    FOREIGN KEY (`ID_Evento`)
    REFERENCES `Evento` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE;

ALTER TABLE `Doacao` ADD CONSTRAINT `FK_Doacao_Doador`
    FOREIGN KEY (`CPF_Doador`)
    REFERENCES `Doador` (`CPF`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE;
	
ALTER TABLE `Doacao` ADD CONSTRAINT `FK_Doacao_ProjetoAssistencial`
    FOREIGN KEY (`ID_ProjetoAssistencial`)
    REFERENCES `ProjetoAssistencial` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE;	
	
ALTER TABLE `Ajuda` ADD CONSTRAINT `FK_Ajuda_ProjetoAssistencial`
    FOREIGN KEY (`ID_ProjetoAssistencial`)
    REFERENCES `ProjetoAssistencial` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE;

ALTER TABLE `Ajuda` ADD CONSTRAINT `FK_Ajuda_Beneficiario`
    FOREIGN KEY (`CPF_Beneficiario`)
    REFERENCES `Beneficiario` (`CPF`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE;
	
ALTER TABLE `ProjetoAssistencial` ADD CONSTRAINT `FK_ProjetoAssistencial_Instituicao`
    FOREIGN KEY (`CNPJ_Instituicao`)
    REFERENCES `Instituicao` (`CNPJ`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE;
	
ALTER TABLE `Relatorio` ADD CONSTRAINT `FK_Relatorio_Instituicao`
    FOREIGN KEY (`CNPJ_Instituicao`)
    REFERENCES `Instituicao` (`CNPJ`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE;
	
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
