-- MySQL Script generated by MySQL Workbench
-- Sun Dec 1 16:33:43 2024
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `FEIG` ;

CREATE SCHEMA IF NOT EXISTS `FEIG` DEFAULT CHARACTER SET utf8 ;

USE `FEIG` ;

DROP TABLE IF EXISTS `Instituicao`;
DROP TABLE IF EXISTS `Voluntarios`;
DROP TABLE IF EXISTS `Doador`;
DROP TABLE IF EXISTS `Beneficiario`;
DROP TABLE IF EXISTS `ProjetoAssistencial`;
DROP TABLE IF EXISTS `Ajuda`;
DROP TABLE IF EXISTS `Evento`;
DROP TABLE IF EXISTS `Doacao`;
DROP TABLE IF EXISTS `Relatorio`;

CREATE TABLE IF NOT EXISTS `Instituicao` (
    `CNPJ` CHAR(14) NOT NULL,
    `Nome` VARCHAR(80) NOT NULL,
    `Telefone` VARCHAR(20) NOT NULL,
    `E-Mail` VARCHAR(45) NOT NULL,
    `Endereco` VARCHAR(100) NOT NULL)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Voluntarios` (
    `CPF` CHAR(11) NOT NULL,
    `Nome` VARCHAR(80) NOT NULL,
    `Telefone` VARCHAR(20) NOT NULL,
    `E-Mail` VARCHAR(45) NOT NULL,
    `CNPJ_Instituicao` CHAR(14) NOT NULL)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Doador` (
    `CPF` CHAR(11) NOT NULL,
    `Nome` VARCHAR(80) NOT NULL,
    `Telefone` VARCHAR(20) NOT NULL,
    `E-Mail` VARCHAR(45) NOT NULL,
    `Endereco` VARCHAR(100) NOT NULL)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Beneficiario` (
    `CPF` CHAR(11) NOT NULL,
    `Nome` VARCHAR(80) NOT NULL,
    `Telefone` VARCHAR(20) NOT NULL,
    `Endereco` VARCHAR(100) NOT NULL,
    `DataNascimento` DATE NOT NULL)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `ProjetoAssistencial` (
    `ID` INT NOT NULL,
    `Nome` VARCHAR(80) NOT NULL,
    `Descricao` VARCHAR(250) NOT NULL,
    `Orcamento` FLOAT NOT NULL,
    `DataInicio` DATE NOT NULL,
    `DataFim` DATE NOT NULL,
    `CNPJ_Instituicao` CHAR(14) NOT NULL)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Ajuda` (
    `ID_ProjetoAssistencial` INT NOT NULL,
    `CPF_Beneficiario` CHAR(11) NOT NULL)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Evento` (
    `ID` INT NOT NULL,
    `Nome` VARCHAR(80) NOT NULL,
    `Localizacao` VARCHAR(100) NOT NULL,
    `Data` DATE NOT NULL)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Doacao` (
    `ID` INT NOT NULL,
    `Descricao` VARCHAR(250) NOT NULL,
    `Tipo` VARCHAR(45) NOT NULL,
    `Quantidade` FLOAT NOT NULL,
    `Data` DATE NOT NULL,
    `ID_Evento` INT,
    `CPF_Doador` CHAR(11) NOT NULL,
    `ID_ProjetoAssistencial` INT)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `Relatorio` (
    `ID` INT NOT NULL,
    `Descricao` VARCHAR(250) NOT NULL,
    `DataPublicacao` DATE NOT NULL,
    `TotalGasto` FLOAT NOT NULL,
    `TotalArrecadado` FLOAT NOT NULL,
    `CNPJ_Instituicao` CHAR(14) NOT NULL)
ENGINE = InnoDB;
